#!/usr/bin/env bash

getent group prometheus > /dev/null 2>&1 || groupadd prometheus
getent passwd prometheus > /dev/null 2>&1 || useradd -g prometheus -d /opt/prometheus -m -s /bin/bash prometheus > /dev/null