#!/usr/bin/env bash

if getent group prometheus > /dev/null; then
  # group exists
else
  groupadd -g 1700 prometheus
fi

if getent passwd prometheus > /dev/null; then
  # user exists
else
  useradd -d /opt/prometheus -m -s /bin/bash prometheus > /dev/null
fi
